title: Dostępnik
description: Zbieranina informacji o dostępności.
lang: "pl"
theme: agency-jekyll-theme
author: Jacek Zadrożny
email: jaczad@gmail.com
url: "https://JacZad.github.io"
kramdown:
  input: GFM
format_date: "%-d %B %Y"
# date_format: "%D %M %Y"
# Ustawienia permalinków
permalink: /:title/



menu:
  - title: "O mnie"
    url: /aboutme
  - title: "Newsletter"
    url: https://dostepnik.substack.com




exclude:
  - .github/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - README.md
 